- dreadnode/api/client.py
- summary routes were missing some required attributes
-  routes are intended and include additional details
**Changed:**
---
- Updated API endpoints in `ApiClient` for fetching run tasks and traces.
- Changed the GET request URL for tasks from `/tasks` to `/tasks/full`, which might return more detailed task information.
- Changed the GET request URL for spans from `/spans` to `/spans/full`, likely providing additional context for trace spans.
- These modifications should improve the detail and usability of the data returned by the API related to run tasks and spans.
> fix: switched API client routes to full routes

- dreadnode/api/client.py
- dreadnode/api/models.py
- dreadnode/api/util.py
- poetry.lock
- pyproject.toml
- Replaced `Run` with `RunSummary` in the `list_runs` method of `ApiClient` to return more aggregated run information.
- Introduced `_get_run` as a private method in `ApiClient` to improve encapsulation while maintaining an existing `get_run` method that now processes run information through the `process_run` utility function, enhancing data integrity.
- Updated `get_run_tasks` to now convert tasks into `Task` objects processed with the context of `RawRun`, allowing for deeper integration of run context with tasks.
- Modified the `get_run_trace` logic to enhance how task and trace spans are constructed, introducing better error handling and readability.
- Created a new utility module with functions `process_run` and `process_task`, separating concerns and improving the maintainability of …
> fix: API-level task/run input and output handling

- .pre-commit-config.yaml
- dreadnode/__init__.py
- dreadnode/data_types/audio.py
- dreadnode/main.py
- dreadnode/task.py
- dreadnode/tracing/constants.py
- dreadnode/tracing/span.py
- poetry.lock
- pyproject.toml
- Add get_run_context and continue_run features.
- Fix dependencies and some pre-commit stuff
Example:
```py
import asyncio
import threading
import time
from concurrent.futures import ThreadPoolExecutor
import dreadnode
dreadnode.configure()
NAMES = ["Nick", "Will", "Brad", "Brian"]
@dreadnode.task()
async def say_hello(name: str) -> str:
return f"Hello, {name}!"
def process_in_thread(name: str, run_context) -> str:
"""Simulates work happening in another thread/process"""
with dreadnode.continue_run(run_context) as remote_run:
remote_run.log_param("thread_id", threading.get_ident())
remote_run.log_param("processed_name", name)
asyncio.run(say_hello(name))
remote_run.log_metric("processing_time", 0.5)
remote_run.log_metric("name_length", len(name))
result = f"Processed {name} in thread …
```
> feat: Remote Run Context

- docs/how-to/airtbench-agent.mdx
> docs: add arxiv reference 2506.14682 to airtbench agent docs

- dreadnode/api/models.py
Updates the `RunSummary.id` field type annotation to accept both `ULID` and `str` types.
- Modified `RunSummary.id` type from `ULID` to `ULID | str` in the RunSummary model
This change provides more flexibility for the `id` field, allowing it to accept string representations in addition to proper ULID objects. This is useful for scenarios where:
- IDs are received as strings from external APIs or serialized data
- Backward compatibility is needed with existing string-based ID implementations
---
- Updated the `id` field in the `RunSummary` model to support both `ULID` and `str` types.
- This change enhances flexibility in handling different identifier formats for runs.
- The data model now allows for backward compatibility and potential integration with other services that may use string …
> fix: changed run id type to ULID | str to accomodate old data types

- dreadnode/tracing/span.py
- Uses w3c_propagator for distributed trace run continuation
---
- Introduced handling for cases when the global propagator is a NoExtract instance.
- Added a fallback mechanism to use the W3C propagator directly with `TraceContextTextMapPropagator`.
- Modified context attachment logic to ensure it only occurs if the trace_id from the span context is valid.
- Implemented a clearer fallback behavior by creating a new span if the provided context is invalid.
- These changes enhance the robustness of tracing context propagation, ensuring that traces can continue under more conditions.
> fix: distributed propagation

- pyproject.toml
- Bump Version to V1.0.8
---
- Updated version from `1.0.7` to `1.0.8` in `pyproject.toml`.
- This change reflects a new release of the Dreadnode SDK.
- No functional changes to the codebase; changes are versioning only.
- Ensures compatibility with Python versions `>=3.10,<3.14`.
> chore: Bump Version to V1.0.8

- README.md
- pyproject.toml
- fix: Update Readme with Correct PyPI Package Installation
---
- Updated version of the `dreadnode` package from `1.0.9` to `1.10.0`.
- Corrected installation command formatting in the README to use proper quotation marks for optional features.
- Ensures that installation instructions are clearer and will function correctly for users.
- No functional changes to the codebase; primarily documentation and version increment.
> fix: Update Readme with Correct PyPI Package Installation

- docs/sdk/api.mdx
- docs/sdk/data_types.mdx
- docs/sdk/main.mdx
- dreadnode/main.py
- dreadnode/task.py
- dreadnode/util.py
- Add the ability for tasks to execute outside of runs without raising errors in common `__call__` scenarios
---
- Updated metric value type in documentation from `float` to `float | None` to indicate optional values.
- Changed run and object linking method usage in examples from `run.link_objects()` to `dreadnode.link_objects()`, ensuring consistency across usage.
- Introduced checks for optional dependencies (like audio, image, and video processing) with clear error messages upon import failures, improving user experience.
- Updated method signatures and examples to use `dreadnode` methods directly instead of instance methods for clarity and simplicity.
- Modified string cleaning function to support `@` character in addition to `/`, enhancing its utility in various contexts.
- Added a …
> fix: Tasks outside runs

- docs/usage/runs.mdx
- docs/usage/tasks.mdx
- dreadnode/__init__.py
- dreadnode/convert.py
- dreadnode/tracing/span.py
Key Changes:
- Add task hierarchy and relationship tracking to span objects
- Implement __repr__ and __str__ methods on span objects
- Add navigation properties for parent/child task relationships
Added:
- Task hierarchy properties: tasks, all_tasks, parent_task
- Run-level task tracking with run.tasks and run.all_tasks
- String representation methods for all span classes
- `.failed` property to check span error status
- Helper function _format_status for consistent status display
Changed:
- Task span initialization now establishes parent-child relationships
- Documentation updated to showcase new hierarchy features
- Context management improved to maintain task relationships
---
- Added a new section on "Task Hierarchy and Relationships" in both the `runs.mdx` and `tasks.mdx` …
> feat: Task Hierarchy

- docs/sdk/main.mdx
- dreadnode/main.py
- dreadnode/tracing/span.py
- pyproject.toml
- Refactored many places where `RuntimeError`s were being thrown when calls were made outside of tasks/runs and migrated them to warnings that gracefully fail
---
- Updated multiple functions to replace `RuntimeError` with `warn_at_user_stacklevel`, improving user feedback when methods are called outside of a valid run context.
- Functions affected:
- `link_objects`
- `log_artifact`
- `log_input`
- `log_metric`
- `log_metrics`
- `log_output`
- `log_params`
- `push_update`
- `tag`
- Bumped version from `1.11.0` to `1.11.1` in `pyproject.toml` reflecting these changes.
- Enhanced the user experience by providing warnings instead of raising exceptions, reducing potential disruptions in workflow.
> hotfix: Live run/task errors

- docs/docs.json
- docs/examples.mdx
- docs/examples/agent-examples.mdx
- docs/examples/dangerous-capabilities.mdx
- docs/examples/dotnet-reversing.mdx
- docs/examples/python-agent.mdx
- docs/examples/saas-scanning.mdx
- docs/examples/sensitive-data.mdx
** Added **
- new examples section under "Getting Started"
- new docs pages for each of the example agents
** Removed **
- redirect link to examples repo from nav
> docs: agent card docs

- .github/workflows/test.yaml
Caching was causing non-deterministic typing errors between the different versions of Python
**Removed:**
---
- Removed caching of dependencies in GitHub Actions workflow.
- Caching previously utilized `.venv` directory to improve package install speed.
- Potential impact: Slight increase in install time for dependencies, as caching will no longer be used.
- Adjusts workflow to focus solely on the installation step with Poetry.
> fix: remove caching from CI test workflow

- .hooks/generate_docs.py
- dreadnode/agent/agent.py
- dreadnode/agent/events.py
- dreadnode/agent/hooks/summarize.py
- dreadnode/api/client.py
- dreadnode/cli/agent/cli.py
- dreadnode/cli/main.py
- dreadnode/cli/profile/cli.py
- dreadnode/convert.py
- dreadnode/data_types/audio.py
- dreadnode/data_types/image.py
- dreadnode/data_types/table.py
- dreadnode/data_types/video.py
- dreadnode/main.py
- dreadnode/scorers/classification.py
- dreadnode/scorers/harm.py
- dreadnode/scorers/pii.py
- dreadnode/scorers/rigging.py
- dreadnode/scorers/similarity.py
- dreadnode/serialization.py
- dreadnode/tracing/span.py
- poetry.lock
- pyproject.toml
**Changed:**
---
- Updated development dependencies in `pyproject.toml`:
- **mypy** version upgraded from `1.8.0` to `1.17.0`
- **ruff** version upgraded from `0.11.6` to `0.12.0`
- **pre-commit** version upgraded from `4.0.0` to `4.3.0`
- **mkdocstrings-python** version upgraded from `1.16.12` to `1.17.0`
- These updates may improve compatibility, add new features, and fix existing issues within the development workflow.
> chore: updated dev deps

- .github/workflows/docs-update.yaml
- .github/workflows/meta-labeler.yaml
- .github/workflows/meta-sync-labels.yaml
- .github/workflows/pre-commit.yaml
- .github/workflows/renovate.yaml
- .github/workflows/rigging_pr_description.yaml
- .github/workflows/semantic-prs.yaml
- .github/workflows/semgrep.yaml
- .github/workflows/template-sync.yaml
**Changed:**
---
- Updated `create-github-app-token` action from v2.0.6 to v2.1.1 in multiple workflows to benefit from the latest fixes and improvements.
- Upgraded `checkout` action from v4.2.2 to v5.0.0 across various workflows for enhanced performance and features.
- Updated `action-semantic-pull-request` from v5.5.3 to v6.1.0 to leverage new validations and capabilities.
- These changes may improve the stability and functionality of the GitHub workflows, ensuring that they run more efficiently.
> chore: updated task versions

- dreadnode/cli/platform/constants.py
- dreadnode/cli/platform/docker_.py
- dreadnode/cli/platform/status.py
- uses container names to check available and required containers before login attempts
- better checking of running
- uses version tags vs sha hashes in env vars
- renamed some of the env var files and service names (specific to Dreadnode)
---
- Updated the `PlatformService` literal to use "dreadnode-api" and "dreadnode-ui" instead of "api" and "ui".
- Introduced new functions in `docker_.py`:
- `_build_docker_compose_base_command`: Constructs the base Docker Compose command from the selected version.
- `get_required_service_names`: Retrieves required service names from the Docker Compose file.
- Enhanced the equality check (`__eq__`) in the `DockerImage` class to compare digests and tags conditionally.
- Removed redundant checks for Docker and Docker Compose …
> feat: better version and container handling

- dreadnode/cli/platform/docker_.py
- dreadnode/cli/platform/start.py
If a self-hosted platform user is connecting to a remote database, we don't need to provide containers for the same service. By using "profiles" in the Docker Compose file, we can conditionally start the containers. Additionally, we can use a custom attribute in the compose file `x-override.` to see if the profile should be included.
- the `platform start` builds a `profile` list based on compose env
**Added:**
- profile building method to check for profile attrs and `x-override` attrs.
---
- Introduced `DockerError` exception to provide more specific error handling for Docker-related errors.
- Added a new function `_get_profiles_to_enable` that determines which Docker profiles should be enabled based on the presence of environment variables.
- Modified the …
> feat: checks for profiles and env vars for conditional services

- pyproject.toml
- Include examples folder in PyPI package
Customer note: Example scripts are now bundled in the package to help get started quickly.
---
- Updated the `pyproject.toml` file to include the `/examples` directory in the source distribution (sdist) build.
- This change allows users to access example code when installing the package from the source distribution.
- No changes were made to package dependencies or functionality.
> chore: add examples folder to pypi distribution

- docs/docs.json
- adding sections to the SDK docs for easier finding
**Changed:**
- Updated SDK docs to now have three new subsections
---
- Updated the documentation structure for the SDK in `docs/docs.json`.
- Introduced three new groups: 
- Core
- Data and Processing
- Evaluation and Integrations
- Each group contains relevant pages that were previously listed individually.
- Enhances organization and accessibility of SDK documentation.
- Potentially improves onboarding and navigation for developers using the SDK.
> add IA structure to SDK repo

- dreadnode/__init__.py
- dreadnode/agent/__init__.py
- dreadnode/agent/agent.py
- dreadnode/agent/tools/__init__.py
- dreadnode/agent/tools/base.py
- uv.lock
- Fixed a bug where `PrivateAttr` fields on tools would get wiped due to round trip model construction caused by generics on the Agent `.tools` field.
- Adjusted some imports to make it easier to access `Agent`, `@tool`, and `@tool_method`.
---
- Added imports for `Agent`, `tool`, and `tool_method` in `dreadnode/__init__.py`.
- Updated the `__all__` exports to include `Agent`, `tool`, and `tool_method`, ensuring they are accessible at the package level.
- Enhanced lazy component registrations to include `Agent`, `tool`, and `tool_method` in `__lazy_components__`.
- Imported `tool` and `tool_method` in `dreadnode.agent` to ensure their availability across agent modules.
- Refined the type annotations of `tools` in the `Agent` class to use `t.Annotated` with `SkipValidation`, which improves …
> fix: Agent tool generics

- dreadnode/agent/agent.py
- dreadnode/agent/events.py
- dreadnode/agent/hooks/__init__.py
- dreadnode/agent/hooks/backoff.py
- dreadnode/agent/reactions.py
- Add `backoff_on_error` and `backoff_on_ratelimit` hooks for agents.
- Add unique session_id for an agent run session (needed so we can properly track backoff)
---
- Introduced `session_id` of type `ULID` to uniquely identify agent run sessions.
- Enhanced `AgentEvent` to include `session_id`, improving traceability for events.
- Updated multiple event dispatch calls to include the `session_id`, ensuring consistent session tracking.
- Import from `ulid` added across relevant files to support the new identifier.
- Adjusted the `messages` field in the `Retry` reaction class to have a default value, making it optional.
- Changes may improve debugging and performance by providing a clear link between events and their corresponding sessions.
This summary was generated with ❤️ by …
> feat: Backoff hooks
